export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <body className="min-h-screen flex flex-col">
        <header style={{
          backgroundColor: 'lightblue',
          padding:'1rem',
        }} >Header</header>
        
        <main className="flex-grow">{children}</main>
        <footer style={{
          backgroundColor: 'lightblue',
          padding:'1rem',
        }}>Footer</footer>
      </body>
    </html>
  );
}
